version: '3.7'

services:
   backend:
     build: .
     image: webvirtcloud:latest
     ports:
       - "8000:8000"
     volumes:
     - ./backend:/app
     command: python3 manage.py runserver 0:8000
     environment:
       DB_HOST: mariadb
       DB_USER: root
       DB_PASSWORD: root
       DJANGO_SETTINGS_MODULE: webvirtcloud.settings.dev
       BROKER_URL: "amqp://guest:guest@rabbitmq:5672"
     depends_on:
       - rabbitmq
       - mariadb
   mariadb:
     image: mariadb:latest
     volumes:
     - ./dbdata:/var/lib/mysql
     ports:
     - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
   rabbitmq:
     image: rabbitmq:latest
